#!/usr/bin/env python3
"""Generate the claim-binding view; reject broken and unreachable bindings.

Usage: python3 scripts/build_pairings.py [--shared DIR] [--check]
The generated pairings.md is ignored deployment material. Edit the canonical
claims/taxonomy, never this view. No network calls or approval effects.
"""
import argparse
import json
import sys
from pathlib import Path

import factory

SHARED = factory.SHARED


def build(shared=SHARED):
    tax = factory.taxonomy(shared)
    doc = factory.claim_document(shared)
    rows = {r["id"]: r for r in doc["claims"]}
    reachable, problems = set(), []
    lines = [
        "# Signal to claim pairings", "",
        "Generated by `scripts/build_pairings.py`. Edit taxonomy.json or claims.json, then rebuild.", "",
        f"Source revision: `{doc.get('source_revision') or 'unconfigured'}`. Evidence checked: `{doc.get('evidence_verified') or 'unverified'}`.", "",
        "Select by the signal quote and creates_work; persona shapes wording and the question, not candidate selection. Follow workflows/outreach/signal-outreach.md for candidates, fallback and relevance. Report the runner-up and quote-to-claim pick_reason. Fit-mode warnings never waive claim approval, holds, evidence or recipient checks.", "",
    ]
    for tier in ("tier1", "tier2"):
        lines += ["## " + tier, ""]
        for signal in tax["tiers"][tier]:
            lines += [
                "### " + signal["id"], "", signal["definition"], "",
                f"Fresh for {signal['freshness_days']} days. Source: {signal.get('source', 'web')}.",
                "Work: " + signal["creates_work"],
                "Recipient titles: " + ", ".join(signal["target_titles"]), "",
            ]
            for rid in signal["claim_ids"]:
                if rid not in rows:
                    problems.append("unknown claim: " + rid)
                    continue
                reachable.add(rid)
                row = rows[rid]
                lines += [
                    f"- `{rid}` ({row['kind']}, {row['status']})",
                    "  Track: " + row["track"], "  Claim: " + row["claim"], "  Limit: " + row["limit"],
                    "  Personas: " + ", ".join(row["personas"]) + "; verticals: " + ", ".join(row["verticals"]),
                    "  Source: " + row["source_reference"],
                ]
                if rid in doc.get("held", []):
                    lines.append("  Held: unavailable for outreach.")
                proof = row.get("proof") or {}
                if proof.get("name"):
                    lines.append(f"  Proof: {proof['name']}; external naming: {str(proof['external_ok']).lower()}.")
            lines.append("")
    problems += ["unreachable claim: " + rid for rid in sorted(set(rows) - reachable)]
    return "\n".join(lines).rstrip() + "\n", problems


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shared", type=Path, default=SHARED)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        text, problems = build(args.shared)
        output = args.shared / "pairings.md"
        if output.is_symlink():
            raise ValueError("pairings output must not be a symlink")
        stale = not output.exists() or output.read_text() != text
        written = False
        if not args.check and not problems:
            output.write_text(text)
            stale, written = False, True
        print(json.dumps({"stale": stale, "written": written, "problems": problems}))
        return int(bool(problems or (args.check and stale)))
    except (ValueError, KeyError, TypeError, OSError) as exc:
        print(json.dumps({"verdict": "error", "reason": str(exc)}))
        return 2


if __name__ == "__main__":
    sys.exit(main())
